/*
 * Federated Wiki : Pharo Script Plugin
 *
 * Licensed under the MIT license.
 * https://github.com/fedwiki/wiki-plugin-pharoscript/blob/master/LICENSE.txt
 */
var escape;

escape = function(str) {
  return String(str).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#39;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
};

window.plugins.pharoscript = (function() {
  var load;

  function pharoscript() {}

  load = function(callback) {
    wiki.getScript('/plugins/pharoscript/prettify.js', callback);
    if (!$("link[href='/plugins/pharoscript/prettify.css']").length) {
      return $('<link href="/plugins/pharoscript/prettify.css" rel="stylesheet" type="text/css">').appendTo("head");
    }
  };

  pharoscript.emit = function(div, item) {
    return load(function() {
      return div.append("<pre class='prettyprint'>" + (prettyPrintOne(escape(item.text))) + "</pre>");
    });
  };

  pharoscript.bind = function(div, item) {
    return load(function() {
      return div.dblclick(function() {
        return wiki.textEditor(div, item);
      });
    });
  };

  return pharoscript;

})();

// ---
// generated by coffee-script 1.9.2